#!/usr/bin/env bash
#
# One-time setup for the workshop environment. Installs dependencies for both
# apps, initialises the database, and pre-downloads/pre-builds everything the
# dev servers need so that the first run is fast.
#
# Safe to re-run: every step is idempotent.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

step() { printf '\n\033[1;36m==> %s\033[0m\n' "$1"; }
warn() { printf '\033[1;33mWARNING: %s\033[0m\n' "$1" >&2; }

step "Checking Pushpin is available"
if command -v pushpin >/dev/null 2>&1; then
  echo "Found $(command -v pushpin) — $(pushpin --version 2>&1 | head -1)"
else
  warn "'pushpin' is not on PATH. The edge app will still build and proxy, but
         Fanout handoff (the realtime SSE stream) will fail. It is normally
         installed by .devcontainer/Dockerfile."
fi

step "Installing Python dependencies (origin)"
if [ ! -d origin/venv ]; then
  python3 -m venv origin/venv
fi
origin/venv/bin/python -m pip install --upgrade pip --quiet
origin/venv/bin/python -m pip install -r origin/requirements.txt --quiet
echo "Using $(origin/venv/bin/python --version)"

step "Creating origin/.env"
if [ -f origin/.env ]; then
  echo "origin/.env already exists, leaving it alone."
else
  secret_key="$(origin/venv/bin/python -c 'import secrets; print(secrets.token_urlsafe(50))')"
  cat > origin/.env <<EOF
# Generated by .devcontainer/setup.sh. Not committed — edit freely.

# Used by Django for signing. Random per environment.
DJANGO_SECRET_KEY="${secret_key}"

# Where the backend publishes realtime messages to.
#
# In production this is a Fastly API URL, and messages are published through
# Fanout. Locally it points at Pushpin's publish handler, which the Fastly CLI
# starts for us on port 5561 (see [local_server.pushpin] in edge/fastly.toml).
GRIP_URL="http://127.0.0.1:5561/"
EOF
  echo "Wrote origin/.env with a freshly generated secret key."
fi

step "Setting up the database (origin)"
(cd origin && ./venv/bin/python manage.py migrate)

step "Installing JavaScript dependencies (edge)"
(cd edge && npm install --no-fund --no-audit)

step "Configuring the Fastly CLI"
# The CLI otherwise asks about build metadata collection the first time it
# builds, which would hang when the dev server is started unattended.
(cd edge && npx fastly compute metadata --disable) >/dev/null 2>&1 \
  || warn "Could not pre-set the CLI metadata preference."

step "Downloading the local Fastly dev server (Viceroy)"
# `fastly compute serve` fetches Viceroy on first use. Doing it now means the
# first run doesn't stall on a download — and lets prebuilds cache it.
(cd edge && npx fastly compute install-tools --non-interactive) \
  || warn "Could not pre-download Viceroy; 'fastly compute serve' will fetch it on first run."

step "Pre-building the Wasm package (edge)"
(cd edge && npm run build) \
  || warn "Pre-build failed; 'scripts/dev.sh' will try again when it starts."

step "Setup complete"
cat <<'EOF'
The dev servers start automatically when you attach to the container.

Useful commands:
  scripts/dev.sh            start both apps (or tail logs if already running)
  scripts/dev.sh restart    restart both apps
  scripts/dev.sh stop       stop both apps
  scripts/dev.sh status     show what's running

Then open the forwarded port 7676 in your browser.
EOF
